### ISSUE TITLE
torchvision.models.swin_transformer

### ISSUE THREAD

**Issue by 622tongtong** [bityangtian/FPNFormer#2]
from torchvision.models.swin_transformer import SwinTransformerBlock
Hi,
   Thank for your sharing. 
   I cannot get torchvision.models.swin_transformer, can you tell me how to get it?

**Comment by yangtian6781** [comment]
please make sure you have installed torchvision.
you could try these command:
# CUDA 11.6
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia
# CUDA 11.7
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia

**Comment by 622tongtong** [comment]
thank you so much! maybe it is because my torch version is too low
